### ISSUE TITLE
robot-master status board yields internal server error intermittantly

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/robot-master#43]
https://sul-lyberservices-prod.stanford.edu/robots/statusboard

in production the status board sometimes comes back with "Internal Server Error" and no other information.

**Comment by drh-stanford** [comment]
Full exception from httpd error_log:

```
App 5062 stderr: 2016-07-11 10:49:25 - RestClient::RequestTimeout - Request Timeout:
App 5062 stderr: 	/home/lyberadmin/robot-master/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:427:in `rescue in transmit'
App 5062 stderr: 	/home/lyberadmin/robot-master/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:350:in `transmit'
App 5062 stderr: 	/home/lyberadmin/robot-master/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
App 5062 stderr: 	/home/lyberadmin/robot-master/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
App 5062 stderr: 	/home/lyberadmin/robot-master/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
App 5062 stderr: 	/home/lyberadmin/robot-master/releases/20160304203912/lib/robot-master/status_board.rb:9:in `count_ready'
App 5062 stderr: 	/home/lyberadmin/robot-master/releases/20160304203912/lib/robot-master/status_board.rb:37:in `block (2 levels) in map_workflow'
App 5062 stderr: 	/home/lyberadmin/robot-master/shared/bundle/ruby/2.2.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
App 5062 stderr: 	/home/lyberadmin/robot-master/shared/bundle/ruby/2.2.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
App 5062 stderr: 	/home/lyberadmin/robot-master/shared/bundle/ruby/2.2.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
App 5062 stderr: 	/home/lyberadmin/robot-master/releases/20160304203912/lib/robot-master/status_board.rb:36:in `block in map_workflow'
App 5062 stderr: 	/home/lyberadmin/robot-master/shared/bundle/ruby/2.2.0/gems/parallel-1.6.2/lib/parallel.rb:408:in `call'
App 5062 stderr: 	/home/lyberadmin/robot-master/shared/bundle/ruby/2.2.0/gems/parallel-1.6.2/lib/parallel.rb:408:in `call_with_index'
App 5062 stderr: 	/home/lyberadmin/robot-master/shared/bundle/ruby/2.2.0/gems/parallel-1.6.2/lib/parallel.rb:288:in `block (2 levels) in work_in_threads'
App 5062 stderr: 	/home/lyberadmin/robot-master/shared/bundle/ruby/2.2.0/gems/parallel-1.6.2/lib/parallel.rb:419:in `with_instrumentation'
App 5062 stderr: 	/home/lyberadmin/robot-master/shared/bundle/ruby/2.2.0/gems/parallel-1.6.2/lib/parallel.rb:287:in `block in work_in_threads'
App 5062 stderr: 	/home/lyberadmin/robot-master/shared/bundle/ruby/2.2.0/gems/parallel-1.6.2/lib/parallel.rb:183:in `block (2 levels) in in_threads'
```
